/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());

        int[][] weeklyMonthTemperatures = new int[][]{
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] analyzeweatherdataexpected = new int[]{72,51,63,67,68,69};

        int[] analyzeweatherdata =  classUnderTest.analyzeweatherdata(weeklyMonthTemperatures);
        assertArrayEquals(analyzeweatherdataexpected, analyzeweatherdata);
    }
}
