/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

    }
    public static  int[] analyzeweatherdata(int[][] data)
    {
        HashSet<Integer> uniquetempshasset = new HashSet<Integer>();
        HashMap<String,Integer> minmaxtemp = new HashMap<>();
        minmaxtemp.put("min",100);
        minmaxtemp.put("max",0);

        for(int i=0; i<4; i++){
            for(int j=0;j<7; j++) {
             //   System.out.println(data[i][j]);


                uniquetempshasset.add(data[i][j]);

                if(data[i][j]>minmaxtemp.get("max")){
                    minmaxtemp.put("max", data[i][j]);
                }
                if(data[i][j]<minmaxtemp.get("min")){
                    minmaxtemp.put("min", data[i][j]);
                }
            }
        }
        System.out.println("High: " + minmaxtemp.get("max"));
        System.out.println("Low: " + minmaxtemp.get("min"));
        int analyzeddata[];
        analyzeddata = new int[6];
        analyzeddata[0]=minmaxtemp.get("max");
        analyzeddata[1]=minmaxtemp.get("min");
        int l=0;
       for(int k=minmaxtemp.get("min"); k< minmaxtemp.get("max");k++){
           Iterator uniquetempshassetval = uniquetempshasset.iterator();
         //  System.out.println("k value"+k);
           boolean found =false;
           while (uniquetempshassetval.hasNext()){
               int uniquetemp = (int)uniquetempshassetval.next();
               if(uniquetemp == k) {
                found=true;
               }
          // System.out.println(uniquetemp);
        }

           if (!found){
               l=l+1;
               System.out.println("Never saw temperature: " + k);
               analyzeddata[l+1]=k;
           }
        }
        return analyzeddata;
    }

}
