/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public int[] roll(int n) {
        int sides = 6;
        int i = 0;
        int[] rolled;
        rolled = new int[n];
        for (i = 0; i < n; i++) {
            int rolledNum = (int) (Math.random() * sides) + 1;
            rolled[i] = rolledNum;
        }
        return rolled;
    }
}